import pytholog as pl

pr_kb = pl.KnowledgeBase()
pr_kb([
    "prescription_for(asthma, inhalers)",
    "prescription_for(diabetes, insulin_therapy)",
    "prescription_for(high_blood_pressure, ace_inhibitors)",
    "prescription_for(arthritis, nsaids)",
    "prescription_for(depression, ssris)",
    "prescription_for(cancer, chemotherapy)",
    "prescription_for(schizophrenia, antipsychotics)",
    "prescription_for(obesity, diet_and_exercise_plan)",
    "prescription_for(chronic_obstructive_pulmonary_disease, bronchodilators)",
    "prescription_for(osteoporosis, bisphosphonates)",
    "prescription_for(hiv_aids, antiretroviral_therapy)",
    "prescription_for(migraine, triptans)",
    "prescription_for(heart_disease, statins)",
    "prescription_for(ulcerative_colitis, immunosuppressants)",
    "prescription_for(parkinsons, levodopa)",
    "prescription_for(glaucoma, eye_drops)",
    "prescription_for(kidney_disease, dialysis)",
    "prescription_for(hepatitis, antiviral_medications)",
    "prescription_for(allergies, antihistamines)",
    "prescription_for(cold, nasal_spray)",
    "prescription_for(flu, flu_shot)",
    "prescription_for(bronchitis, antibiotics)",
    "prescription_for(pneumonia, antibiotics)",
    "prescription_for(sinusitis, antibiotics)",
    "prescription_for(ear_infection, antibiotics)",
    "prescription_for(toothache, antibiotics)",
    "prescription_for(back_pain, pain_relievers)",
    "prescription_for(headache, pain_relievers)",
    "prescription_for(stomach_pain, pain_relievers)",
    "prescription_for(joint_pain, pain_relievers)",
    "prescription_for(muscle_pain, pain_relievers)",
    "prescription_for(knee_pain, pain_relievers)",
    "prescription_for(shoulder_pain, pain_relievers)",
    "prescription_for(neck_pain, pain_relievers)",
])

tr_kb = pl.KnowledgeBase()
tr_kb([
    "treatment_plan_for(asthma, avoid_active_sport)",
    "treatment_plan_for(diabetes, dietary_plan)",
    "treatment_plan_for(high_blood_pressure, lifestyle_changes)",
    "treatment_plan_for(arthritis, lifestyle_modifications)",
    "treatment_plan_for(depression, spenfding_more_time_with_family)",
    "treatment_plan_for(cancer, targeted_therapy)",
    "treatment_plan_for(schizophrenia, social_support_groups)",
    "treatment_plan_for(obesity, more_exercise_and_lifestyle_modifications)",
    "treatment_plan_for(chronic_obstructive_pulmonary_disease, quit_smoking_and_exercise)",
    "treatment_plan_for(osteoporosis, weight_bearing_exercise)",
    "treatment_plan_for(hiv_aids, regular_checkups_and_medications)",
    "treatment_plan_for(migraine, avoid_triggers_and_take_medications)",
    "treatment_plan_for(heart_disease, cardiologist_consultation_and_medications)",
    "treatment_plan_for(ulcerative_colitis, surgery_and_medications)",
    "treatment_plan_for(parkinsons, medication_and_exercise_or_deep_brain_stimulation)",
    "treatment_plan_for(glaucoma, laser_surgery_and_medications)",
    "treatment_plan_for(kidney_disease, lifestyle_modifications_and_medications)",
    "treatment_plan_for(hepatitis, medication_and_diet)",
    "treatment_plan_for(allergies, diet_and_medications_in_case_of_reactions)",
    "treatment_plan_for(cold, rest_and_medications_and_alot_of_water)",
    "treatment_plan_for(flu, rest_and_medications_and_alot_of_water)",
    "treatment_plan_for(bronchitis, hospitalisation_and_medications)",
    "treatment_plan_for(pneumonia, hospitalisation_and_medications)",
    "treatment_plan_for(sinusitis, nasal_rinse_and_medications)",
    "treatment_plan_for(ear_infection, reduce_swelling_and_medications)",
    "treatment_plan_for(toothache, dental_care_and_medications)",
    "treatment_plan_for(back_pain, massage_and_medications)",
    "treatment_plan_for(headache, rest_and_medications)",
    "treatment_plan_for(stomach_pain, dietary_plan_and_medications)",
    "treatment_plan_for(joint_pain, avoid_active_sport_and_medications)",
    "treatment_plan_for(muscle_pain, rest_and_pain_relievers)",
    "treatment_plan_for(knee_pain, avoing_active_sport_and_medications)",
    "treatment_plan_for(shoulder_pain, rest_and_pain_relievers)",
    "treatment_plan_for(neck_pain, rest_and_pain_relievers)",
])